name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate config
        run: |
          echo "const config = { YOUTUBE_API_KEY: '${{ secrets.YOUTUBE_API_KEY }}', CHANNELS: ['@spokeishere', '@ParrotX2', '@wemmbumc'] };" > config.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: . 